import classifyHelper from './classify';
import createHistoryRecordHelper from './createHistoryRecord';
import getDataFromHtmlHelper from './getDataFromHtml';
import fetchHelper from './fetch';
import transitionEndHelper from './transitionEnd';
import transitionPropertyHelper from './transitionProperty';
import getCurrentUrlHelper from './getCurrentUrl';
import normalizeUrlHelper from './normalizeUrl';
import markSwupElementsHelper from './markSwupElements';
import LinkHelper from './Link';
import cleanupAnimationClassesHelper from './cleanupAnimationClasses';

export const classify = classifyHelper;
export const createHistoryRecord = createHistoryRecordHelper;
export const getDataFromHtml = getDataFromHtmlHelper;
export const fetch = fetchHelper;
export const transitionEnd = transitionEndHelper;
export const transitionProperty = transitionPropertyHelper;
export const getCurrentUrl = getCurrentUrlHelper;
export const normalizeUrl = normalizeUrlHelper;
export const markSwupElements = markSwupElementsHelper;
export const Link = LinkHelper;
export const cleanupAnimationClasses = cleanupAnimationClassesHelper;
