name: E2E tests

on:
  push:
  workflow_dispatch:

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run cypress tests
        uses: cypress-io/github-action@v4.2.2
        with:
          command: npm run ci
