name: Lint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --check src/**/*.{js,mjs}
