name: Lint

on:
  push:
    branches: [main, master, next]
  pull_request:

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint
