# This workflow publishes a package to NPM

name: Publish package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # For OIDC Trusted Publishing

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          registry-url: https://registry.npmjs.org
          node-version-file: .nvmrc
          cache: 'npm'
      - run: npm ci
      - run: npm publish --access public
