name: Bundle size

on:
  push:
    branches: [main, master, next]
  pull_request:

jobs:
  build:
    name: Check bundle size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: preactjs/compressed-size-action@8518045ed95e94e971b83333085e1cb99aa18aa8 # 2.9.0
