# This workflow bumps the package.json version and creates a PR

name: Update package version

on:
  workflow_dispatch:
    inputs:
      segment:
        description: 'Semver segment to update'
        required: true
        default: 'patch'
        type: choice
        options:
        - minor
        - patch

jobs:
  update-version:
    name: Update package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - run: echo "Updating ${{ inputs.segment }} version"
      - name: Update version
        run: npm --no-git-tag-version version ${{ inputs.segment }}
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          base: 'main'
          branch: 'version/automated'
          title: 'Update package version (automated)'
          commit-message: 'Update package version'
          body: 'Automated update to ${{ inputs.segment }} version'
          token: ${{ secrets.DISPATCH_TOKEN }}
